{"protocolVersion":"0.1.1","runnerVersion":null,"pid":16630,"type":"start","time":0}
{"suite":{"id":0,"platform":"vm","path":"/Users/axel/Desktop/Matchup/test/unittest/user_test.dart"},"type":"suite","time":0}
{"test":{"id":1,"name":"loading /Users/axel/Desktop/Matchup/test/unittest/user_test.dart","suiteID":0,"groupIDs":[],"metadata":{"skip":false,"skipReason":null},"line":null,"column":null,"url":null},"type":"testStart","time":2}
{"suite":{"id":2,"platform":"vm","path":"/Users/axel/Desktop/Matchup/test/unittest/message_test.dart"},"type":"suite","time":16}
{"test":{"id":3,"name":"loading /Users/axel/Desktop/Matchup/test/unittest/message_test.dart","suiteID":2,"groupIDs":[],"metadata":{"skip":false,"skipReason":null},"line":null,"column":null,"url":null},"type":"testStart","time":16}
{"suite":{"id":4,"platform":"vm","path":"/Users/axel/Desktop/Matchup/test/unittest/textFormFieldValidator_test.dart"},"type":"suite","time":17}
{"test":{"id":5,"name":"loading /Users/axel/Desktop/Matchup/test/unittest/textFormFieldValidator_test.dart","suiteID":4,"groupIDs":[],"metadata":{"skip":false,"skipReason":null},"line":null,"column":null,"url":null},"type":"testStart","time":17}
{"suite":{"id":6,"platform":"vm","path":"/Users/axel/Desktop/Matchup/test/widgettest/loginSignupPage_test.dart"},"type":"suite","time":20}
{"test":{"id":7,"name":"loading /Users/axel/Desktop/Matchup/test/widgettest/loginSignupPage_test.dart","suiteID":6,"groupIDs":[],"metadata":{"skip":false,"skipReason":null},"line":null,"column":null,"url":null},"type":"testStart","time":21}
{"count":4,"type":"allSuites","time":21}
{"testID":1,"result":"success","skipped":false,"hidden":true,"type":"testDone","time":13327}
{"testID":5,"result":"success","skipped":false,"hidden":true,"type":"testDone","time":13451}
{"group":{"id":8,"suiteID":4,"parentID":null,"name":null,"metadata":{"skip":false,"skipReason":null},"testCount":7,"line":null,"column":null,"url":null},"type":"group","time":13456}
{"test":{"id":9,"name":"valid email returns null","suiteID":4,"groupIDs":[8],"metadata":{"skip":false,"skipReason":null},"line":7,"column":3,"url":"file:///Users/axel/Desktop/Matchup/test/unittest/textFormFieldValidator_test.dart"},"type":"testStart","time":13456}
{"testID":3,"result":"success","skipped":false,"hidden":true,"type":"testDone","time":13462}
{"group":{"id":10,"suiteID":2,"parentID":null,"name":null,"metadata":{"skip":false,"skipReason":null},"testCount":1,"line":null,"column":null,"url":null},"type":"group","time":13463}
{"test":{"id":11,"name":"creating message object","suiteID":2,"groupIDs":[10],"metadata":{"skip":false,"skipReason":null},"line":4,"column":3,"url":"file:///Users/axel/Desktop/Matchup/test/unittest/message_test.dart"},"type":"testStart","time":13463}
{"testID":9,"result":"success","skipped":false,"hidden":false,"type":"testDone","time":13510}
{"testID":11,"result":"success","skipped":false,"hidden":false,"type":"testDone","time":13510}
{"test":{"id":12,"name":"empty email returns error message","suiteID":4,"groupIDs":[8],"metadata":{"skip":false,"skipReason":null},"line":17,"column":3,"url":"file:///Users/axel/Desktop/Matchup/test/unittest/textFormFieldValidator_test.dart"},"type":"testStart","time":13511}
{"testID":12,"result":"success","skipped":false,"hidden":false,"type":"testDone","time":13520}
{"test":{"id":13,"name":"null email returns error message","suiteID":4,"groupIDs":[8],"metadata":{"skip":false,"skipReason":null},"line":28,"column":3,"url":"file:///Users/axel/Desktop/Matchup/test/unittest/textFormFieldValidator_test.dart"},"type":"testStart","time":13521}
{"testID":13,"result":"success","skipped":false,"hidden":false,"type":"testDone","time":13527}
{"test":{"id":14,"name":"save properly trims email","suiteID":4,"groupIDs":[8],"metadata":{"skip":false,"skipReason":null},"line":39,"column":3,"url":"file:///Users/axel/Desktop/Matchup/test/unittest/textFormFieldValidator_test.dart"},"type":"testStart","time":13527}
{"testID":14,"result":"success","skipped":false,"hidden":false,"type":"testDone","time":13531}
{"test":{"id":15,"name":"valid password returns null","suiteID":4,"groupIDs":[8],"metadata":{"skip":false,"skipReason":null},"line":50,"column":3,"url":"file:///Users/axel/Desktop/Matchup/test/unittest/textFormFieldValidator_test.dart"},"type":"testStart","time":13532}
{"testID":15,"result":"success","skipped":false,"hidden":false,"type":"testDone","time":13536}
{"test":{"id":16,"name":"empty password returns error message","suiteID":4,"groupIDs":[8],"metadata":{"skip":false,"skipReason":null},"line":60,"column":3,"url":"file:///Users/axel/Desktop/Matchup/test/unittest/textFormFieldValidator_test.dart"},"type":"testStart","time":13536}
{"testID":16,"result":"success","skipped":false,"hidden":false,"type":"testDone","time":13540}
{"test":{"id":17,"name":"empty password returns error message","suiteID":4,"groupIDs":[8],"metadata":{"skip":false,"skipReason":null},"line":71,"column":3,"url":"file:///Users/axel/Desktop/Matchup/test/unittest/textFormFieldValidator_test.dart"},"type":"testStart","time":13540}
{"testID":17,"result":"success","skipped":false,"hidden":false,"type":"testDone","time":13544}
{"testID":7,"result":"success","skipped":false,"hidden":true,"type":"testDone","time":13564}
{"group":{"id":18,"suiteID":6,"parentID":null,"name":null,"metadata":{"skip":false,"skipReason":null},"testCount":5,"line":null,"column":null,"url":null},"type":"group","time":13565}
{"test":{"id":19,"name":"Sign in successfully with valid email and password","suiteID":6,"groupIDs":[18],"metadata":{"skip":false,"skipReason":null},"line":112,"column":3,"url":"package:flutter_test/src/widget_tester.dart","root_line":51,"root_column":3,"root_url":"file:///Users/axel/Desktop/Matchup/test/widgettest/loginSignupPage_test.dart"},"type":"testStart","time":13565}
{"testID":19,"messageType":"print","message":"══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════\nThe following FileSystemException was thrown running a test:\nCannot open file, path = 'assets/images/logo.png' (OS Error: No such file or directory, errno = 2)\n\nWhen the exception was thrown, this was the stack:\n#0      _File.throwIfError (dart:io/file_impl.dart:645:7)\n#1      _File.openSync (dart:io/file_impl.dart:489:5)\n#2      _File.readAsBytesSync (dart:io/file_impl.dart:549:18)\n#3      bytesForFile (file:///Users/axel/Desktop/Matchup/test/widgettest/assetBundle.dart:34:35)\n#4      new TestAssetBundle (file:///Users/axel/Desktop/Matchup/test/widgettest/assetBundle.dart:12:28)\n#5      makeTestableWidget (file:///Users/axel/Desktop/Matchup/test/widgettest/loginSignupPage_test.dart:12:35)\n#6      main.<anonymous closure> (file:///Users/axel/Desktop/Matchup/test/widgettest/loginSignupPage_test.dart:65:35)\n#7      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:124:25)\n#8      TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:696:19)\n<asynchronous suspension>\n#11     TestWidgetsFlutterBinding._runTest (package:flutter_test/src/binding.dart:679:14)\n#12     AutomatedTestWidgetsFlutterBinding.runTest.<anonymous closure> (package:flutter_test/src/binding.dart:1050:24)\n#18     AutomatedTestWidgetsFlutterBinding.runTest (package:flutter_test/src/binding.dart:1047:15)\n#19     testWidgets.<anonymous closure> (package:flutter_test/src/widget_tester.dart:121:22)\n#20     Declarer.test.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart:171:27)\n<asynchronous suspension>\n#21     Invoker.waitForOutstandingCallbacks.<anonymous closure> (package:test_api/src/backend/invoker.dart:242:15)\n#26     Invoker.waitForOutstandingCallbacks (package:test_api/src/backend/invoker.dart:239:5)\n#27     Declarer.test.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart:169:33)\n#32     Declarer.test.<anonymous closure> (package:test_api/src/backend/declarer.dart:168:13)\n#33     Invoker._onRun.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/invoker.dart:392:25)\n#47     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:384:19)\n#48     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:418:5)\n#49     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)\n(elided 28 frames from class _FakeAsync, package dart:async, package dart:async-patch, and package stack_trace)\n\nThe test description was:\n  Sign in successfully with valid email and password\n════════════════════════════════════════════════════════════════════════════════════════════════════","type":"print","time":13840}
{"testID":19,"error":"Test failed. See exception logs above.\nThe test description was: Sign in successfully with valid email and password","stackTrace":"","isFailure":false,"type":"error","time":13846}
{"testID":19,"result":"error","skipped":false,"hidden":false,"type":"testDone","time":13850}
{"test":{"id":20,"name":"Attempt to sign in with empty email and password field","suiteID":6,"groupIDs":[18],"metadata":{"skip":false,"skipReason":null},"line":112,"column":3,"url":"package:flutter_test/src/widget_tester.dart","root_line":94,"root_column":3,"root_url":"file:///Users/axel/Desktop/Matchup/test/widgettest/loginSignupPage_test.dart"},"type":"testStart","time":13850}
{"testID":20,"messageType":"print","message":"══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════\nThe following FileSystemException was thrown while running async test code:\nCannot open file, path = 'assets/images/logo.png' (OS Error: No such file or directory, errno = 2)\n\nWhen the exception was thrown, this was the stack:\n#0      _File.throwIfError (dart:io/file_impl.dart:645:7)\n#1      _File.openSync (dart:io/file_impl.dart:489:5)\n#2      _File.readAsBytesSync (dart:io/file_impl.dart:549:18)\n#3      bytesForFile (file:///Users/axel/Desktop/Matchup/test/widgettest/assetBundle.dart:34:35)\n#4      new TestAssetBundle (file:///Users/axel/Desktop/Matchup/test/widgettest/assetBundle.dart:12:28)\n#5      makeTestableWidget (file:///Users/axel/Desktop/Matchup/test/widgettest/loginSignupPage_test.dart:12:35)\n#6      main.<anonymous closure>.<anonymous closure> (file:///Users/axel/Desktop/Matchup/test/widgettest/loginSignupPage_test.dart:114:37)\n#7      AutomatedTestWidgetsFlutterBinding.runAsync.<anonymous closure> (package:flutter_test/src/binding.dart:914:22)\n#10     AutomatedTestWidgetsFlutterBinding.runAsync (package:flutter_test/src/binding.dart:912:26)\n#11     WidgetTester.runAsync (package:flutter_test/src/widget_tester.dart:453:17)\n#12     main.<anonymous closure> (file:///Users/axel/Desktop/Matchup/test/widgettest/loginSignupPage_test.dart:95:18)\n#13     testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:124:25)\n#14     TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:696:19)\n<asynchronous suspension>\n#17     TestWidgetsFlutterBinding._runTest (package:flutter_test/src/binding.dart:679:14)\n#18     AutomatedTestWidgetsFlutterBinding.runTest.<anonymous closure> (package:flutter_test/src/binding.dart:1050:24)\n#24     AutomatedTestWidgetsFlutterBinding.runTest (package:flutter_test/src/binding.dart:1047:15)\n#25     testWidgets.<anonymous closure> (package:flutter_test/src/widget_tester.dart:121:22)\n#26     Declarer.test.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart:171:27)\n<asynchronous suspension>\n#27     Invoker.waitForOutstandingCallbacks.<anonymous closure> (package:test_api/src/backend/invoker.dart:242:15)\n#32     Invoker.waitForOutstandingCallbacks (package:test_api/src/backend/invoker.dart:239:5)\n#33     Declarer.test.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart:169:33)\n#38     Declarer.test.<anonymous closure> (package:test_api/src/backend/declarer.dart:168:13)\n#39     Invoker._onRun.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/invoker.dart:392:25)\n#53     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:384:19)\n#54     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:418:5)\n#55     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)\n(elided 30 frames from class _FakeAsync, package dart:async, package dart:async-patch, and package stack_trace)\n════════════════════════════════════════════════════════════════════════════════════════════════════","type":"print","time":13874}
{"testID":20,"error":"Test failed. See exception logs above.\nThe test description was: Attempt to sign in with empty email and password field","stackTrace":"","isFailure":false,"type":"error","time":13875}
{"testID":20,"result":"error","skipped":false,"hidden":false,"type":"testDone","time":13875}
{"test":{"id":21,"name":"Attempt to sign up with valid email and password","suiteID":6,"groupIDs":[18],"metadata":{"skip":false,"skipReason":null},"line":112,"column":3,"url":"package:flutter_test/src/widget_tester.dart","root_line":151,"root_column":3,"root_url":"file:///Users/axel/Desktop/Matchup/test/widgettest/loginSignupPage_test.dart"},"type":"testStart","time":13876}
{"testID":21,"messageType":"print","message":"══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════\nThe following FileSystemException was thrown running a test:\nCannot open file, path = 'assets/images/logo.png' (OS Error: No such file or directory, errno = 2)\n\nWhen the exception was thrown, this was the stack:\n#0      _File.throwIfError (dart:io/file_impl.dart:645:7)\n#1      _File.openSync (dart:io/file_impl.dart:489:5)\n#2      _File.readAsBytesSync (dart:io/file_impl.dart:549:18)\n#3      bytesForFile (file:///Users/axel/Desktop/Matchup/test/widgettest/assetBundle.dart:34:35)\n#4      new TestAssetBundle (file:///Users/axel/Desktop/Matchup/test/widgettest/assetBundle.dart:12:28)\n#5      makeTestableWidget (file:///Users/axel/Desktop/Matchup/test/widgettest/loginSignupPage_test.dart:12:35)\n#6      main.<anonymous closure> (file:///Users/axel/Desktop/Matchup/test/widgettest/loginSignupPage_test.dart:166:35)\n#7      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:124:25)\n#8      TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:696:19)\n<asynchronous suspension>\n#11     TestWidgetsFlutterBinding._runTest (package:flutter_test/src/binding.dart:679:14)\n#12     AutomatedTestWidgetsFlutterBinding.runTest.<anonymous closure> (package:flutter_test/src/binding.dart:1050:24)\n#18     AutomatedTestWidgetsFlutterBinding.runTest (package:flutter_test/src/binding.dart:1047:15)\n#19     testWidgets.<anonymous closure> (package:flutter_test/src/widget_tester.dart:121:22)\n#20     Declarer.test.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart:171:27)\n<asynchronous suspension>\n#21     Invoker.waitForOutstandingCallbacks.<anonymous closure> (package:test_api/src/backend/invoker.dart:242:15)\n#26     Invoker.waitForOutstandingCallbacks (package:test_api/src/backend/invoker.dart:239:5)\n#27     Declarer.test.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart:169:33)\n#32     Declarer.test.<anonymous closure> (package:test_api/src/backend/declarer.dart:168:13)\n#33     Invoker._onRun.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/invoker.dart:392:25)\n#47     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:384:19)\n#48     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:418:5)\n#49     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)\n(elided 28 frames from class _FakeAsync, package dart:async, package dart:async-patch, and package stack_trace)\n\nThe test description was:\n  Attempt to sign up with valid email and password\n════════════════════════════════════════════════════════════════════════════════════════════════════","type":"print","time":13886}
{"testID":21,"error":"Test failed. See exception logs above.\nThe test description was: Attempt to sign up with valid email and password","stackTrace":"","isFailure":false,"type":"error","time":13887}
{"testID":21,"result":"error","skipped":false,"hidden":false,"type":"testDone","time":13888}
{"test":{"id":22,"name":"Attempt to sign up with an email that already exists","suiteID":6,"groupIDs":[18],"metadata":{"skip":false,"skipReason":null},"line":112,"column":3,"url":"package:flutter_test/src/widget_tester.dart","root_line":203,"root_column":3,"root_url":"file:///Users/axel/Desktop/Matchup/test/widgettest/loginSignupPage_test.dart"},"type":"testStart","time":13888}
{"testID":22,"messageType":"print","message":"══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════\nThe following FileSystemException was thrown running a test:\nCannot open file, path = 'assets/images/logo.png' (OS Error: No such file or directory, errno = 2)\n\nWhen the exception was thrown, this was the stack:\n#0      _File.throwIfError (dart:io/file_impl.dart:645:7)\n#1      _File.openSync (dart:io/file_impl.dart:489:5)\n#2      _File.readAsBytesSync (dart:io/file_impl.dart:549:18)\n#3      bytesForFile (file:///Users/axel/Desktop/Matchup/test/widgettest/assetBundle.dart:34:35)\n#4      new TestAssetBundle (file:///Users/axel/Desktop/Matchup/test/widgettest/assetBundle.dart:12:28)\n#5      makeTestableWidget (file:///Users/axel/Desktop/Matchup/test/widgettest/loginSignupPage_test.dart:12:35)\n#6      main.<anonymous closure> (file:///Users/axel/Desktop/Matchup/test/widgettest/loginSignupPage_test.dart:217:37)\n#7      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:124:25)\n#8      TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:696:19)\n<asynchronous suspension>\n#11     TestWidgetsFlutterBinding._runTest (package:flutter_test/src/binding.dart:679:14)\n#12     AutomatedTestWidgetsFlutterBinding.runTest.<anonymous closure> (package:flutter_test/src/binding.dart:1050:24)\n#18     AutomatedTestWidgetsFlutterBinding.runTest (package:flutter_test/src/binding.dart:1047:15)\n#19     testWidgets.<anonymous closure> (package:flutter_test/src/widget_tester.dart:121:22)\n#20     Declarer.test.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart:171:27)\n<asynchronous suspension>\n#21     Invoker.waitForOutstandingCallbacks.<anonymous closure> (package:test_api/src/backend/invoker.dart:242:15)\n#26     Invoker.waitForOutstandingCallbacks (package:test_api/src/backend/invoker.dart:239:5)\n#27     Declarer.test.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart:169:33)\n#32     Declarer.test.<anonymous closure> (package:test_api/src/backend/declarer.dart:168:13)\n#33     Invoker._onRun.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/invoker.dart:392:25)\n#47     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:384:19)\n#48     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:418:5)\n#49     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)\n(elided 28 frames from class _FakeAsync, package dart:async, package dart:async-patch, and package stack_trace)\n\nThe test description was:\n  Attempt to sign up with an email that already exists\n════════════════════════════════════════════════════════════════════════════════════════════════════","type":"print","time":13896}
{"testID":22,"error":"Test failed. See exception logs above.\nThe test description was: Attempt to sign up with an email that already exists","stackTrace":"","isFailure":false,"type":"error","time":13897}
{"testID":22,"result":"error","skipped":false,"hidden":false,"type":"testDone","time":13898}
{"test":{"id":23,"name":"test if circular progress indicator appears when waiting for a firebase call","suiteID":6,"groupIDs":[18],"metadata":{"skip":false,"skipReason":null},"line":112,"column":3,"url":"package:flutter_test/src/widget_tester.dart","root_line":254,"root_column":3,"root_url":"file:///Users/axel/Desktop/Matchup/test/widgettest/loginSignupPage_test.dart"},"type":"testStart","time":13898}
{"testID":23,"messageType":"print","message":"══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════\nThe following FileSystemException was thrown while running async test code:\nCannot open file, path = 'assets/images/logo.png' (OS Error: No such file or directory, errno = 2)\n\nWhen the exception was thrown, this was the stack:\n#0      _File.throwIfError (dart:io/file_impl.dart:645:7)\n#1      _File.openSync (dart:io/file_impl.dart:489:5)\n#2      _File.readAsBytesSync (dart:io/file_impl.dart:549:18)\n#3      bytesForFile (file:///Users/axel/Desktop/Matchup/test/widgettest/assetBundle.dart:34:35)\n#4      new TestAssetBundle (file:///Users/axel/Desktop/Matchup/test/widgettest/assetBundle.dart:12:28)\n#5      makeTestableWidget (file:///Users/axel/Desktop/Matchup/test/widgettest/loginSignupPage_test.dart:12:35)\n#6      main.<anonymous closure>.<anonymous closure> (file:///Users/axel/Desktop/Matchup/test/widgettest/loginSignupPage_test.dart:274:37)\n#7      AutomatedTestWidgetsFlutterBinding.runAsync.<anonymous closure> (package:flutter_test/src/binding.dart:914:22)\n#10     AutomatedTestWidgetsFlutterBinding.runAsync (package:flutter_test/src/binding.dart:912:26)\n#11     WidgetTester.runAsync (package:flutter_test/src/widget_tester.dart:453:17)\n#12     main.<anonymous closure> (file:///Users/axel/Desktop/Matchup/test/widgettest/loginSignupPage_test.dart:257:18)\n#13     testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:124:25)\n#14     TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:696:19)\n<asynchronous suspension>\n#17     TestWidgetsFlutterBinding._runTest (package:flutter_test/src/binding.dart:679:14)\n#18     AutomatedTestWidgetsFlutterBinding.runTest.<anonymous closure> (package:flutter_test/src/binding.dart:1050:24)\n#24     AutomatedTestWidgetsFlutterBinding.runTest (package:flutter_test/src/binding.dart:1047:15)\n#25     testWidgets.<anonymous closure> (package:flutter_test/src/widget_tester.dart:121:22)\n#26     Declarer.test.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart:171:27)\n<asynchronous suspension>\n#27     Invoker.waitForOutstandingCallbacks.<anonymous closure> (package:test_api/src/backend/invoker.dart:242:15)\n#32     Invoker.waitForOutstandingCallbacks (package:test_api/src/backend/invoker.dart:239:5)\n#33     Declarer.test.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart:169:33)\n#38     Declarer.test.<anonymous closure> (package:test_api/src/backend/declarer.dart:168:13)\n#39     Invoker._onRun.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/invoker.dart:392:25)\n#53     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:384:19)\n#54     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:418:5)\n#55     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)\n(elided 30 frames from class _FakeAsync, package dart:async, package dart:async-patch, and package stack_trace)\n════════════════════════════════════════════════════════════════════════════════════════════════════","type":"print","time":13910}
{"testID":23,"error":"Test failed. See exception logs above.\nThe test description was: test if circular progress indicator appears when waiting for a firebase call","stackTrace":"","isFailure":false,"type":"error","time":13910}
{"testID":23,"result":"error","skipped":false,"hidden":false,"type":"testDone","time":13911}
{"success":false,"type":"done","time":13924}
